create table status (status_id bigint generated by default as identity, finish_date timestamp, start_date timestamp not null, status integer not null, task_id bigint not null, primary key (status_id))
create table task (task_id bigint generated by default as identity, create_date timestamp not null, description varchar(255) not null, due_date timestamp, modify_date timestamp, priority integer not null, title varchar(255) not null, primary key (task_id))
alter table status add constraint FKdeckom6eec04u253a21jbuxum foreign key (task_id) references task
create table status (status_id bigint generated by default as identity, finish_date timestamp, start_date timestamp not null, status integer not null, task_id bigint not null, primary key (status_id))
create table task (task_id bigint generated by default as identity, create_date timestamp not null, description varchar(255) not null, due_date timestamp, modify_date timestamp, priority integer not null, title varchar(255) not null, primary key (task_id))
alter table status add constraint FKdeckom6eec04u253a21jbuxum foreign key (task_id) references task
create table status (status_id bigint generated by default as identity, finish_date timestamp, start_date timestamp not null, status integer not null, task_id bigint not null, primary key (status_id))
create table task (task_id bigint generated by default as identity, create_date timestamp not null, description varchar(255) not null, due_date timestamp, modify_date timestamp, priority integer not null, title varchar(255) not null, primary key (task_id))
alter table status add constraint FKdeckom6eec04u253a21jbuxum foreign key (task_id) references task
create table status (status_id bigint generated by default as identity, finish_date timestamp, start_date timestamp not null, status integer not null, task_id bigint not null, primary key (status_id))
create table task (task_id bigint generated by default as identity, create_date timestamp not null, description varchar(255) not null, due_date timestamp, modify_date timestamp, priority integer not null, title varchar(255) not null, primary key (task_id))
alter table status add constraint FKdeckom6eec04u253a21jbuxum foreign key (task_id) references task
create table status (status_id bigint generated by default as identity, finish_date timestamp, start_date timestamp not null, status integer not null, task_id bigint not null, primary key (status_id))
create table task (task_id bigint generated by default as identity, create_date timestamp not null, description varchar(255) not null, due_date timestamp, modify_date timestamp, priority integer not null, title varchar(255) not null, primary key (task_id))
alter table status add constraint FKdeckom6eec04u253a21jbuxum foreign key (task_id) references task
create table status (status_id bigint generated by default as identity, finish_date timestamp, start_date timestamp not null, status integer not null, task_id bigint not null, primary key (status_id))
create table task (task_id bigint generated by default as identity, create_date timestamp not null, description varchar(255) not null, due_date timestamp, modify_date timestamp, title varchar(255) not null, primary key (task_id))
alter table status add constraint FKdeckom6eec04u253a21jbuxum foreign key (task_id) references task
create table status (status_id bigint generated by default as identity, finish_date timestamp, start_date timestamp not null, status integer not null, task_id bigint not null, primary key (status_id))
create table task (task_id bigint generated by default as identity, create_date timestamp not null, description varchar(255) not null, due_date timestamp, modify_date timestamp, priority varchar(255) not null, title varchar(255) not null, primary key (task_id))
alter table status add constraint FKdeckom6eec04u253a21jbuxum foreign key (task_id) references task
create table status (status_id bigint generated by default as identity, finish_date timestamp, start_date timestamp not null, status integer not null, task_id bigint not null, primary key (status_id))
create table task (task_id bigint generated by default as identity, create_date timestamp not null, description varchar(255) not null, due_date timestamp, modify_date timestamp, priority varchar(255) not null, title varchar(255) not null, primary key (task_id))
alter table status add constraint FKdeckom6eec04u253a21jbuxum foreign key (task_id) references task
create table status (status_id bigint generated by default as identity, finish_date timestamp, start_date timestamp not null, status integer not null, task_id bigint not null, primary key (status_id))
create table task (task_id bigint generated by default as identity, create_date timestamp not null, description varchar(255) not null, due_date timestamp, modify_date timestamp, priority varchar(255) not null, title varchar(255) not null, primary key (task_id))
alter table status add constraint FKdeckom6eec04u253a21jbuxum foreign key (task_id) references task
